<a href="https://colab.research.google.com/github/Suhani-Singhal2131/Machine-Learning-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
a=[1,2,3.5,'hello']

In [ ]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,10,3)

array([1, 4, 7])

In [ ]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#Random Generation fuction
np.random.rand(10) # all values are between 0 and 1

array([0.6049065 , 0.45606993, 0.68359163, 0.88319193, 0.3586781 ,
       0.84598095, 0.51906182, 0.33649718, 0.8051744 , 0.26032106])

In [ ]:
np.random.randn(10)  # -3 to 3

array([-0.88564332, -2.90433875, -0.87539451,  0.01287199,  1.09883157,
       -0.33370317,  0.63110418, -1.05438036, -0.2650571 ,  0.30549577])

In [ ]:
np.random.randint(6) #generates random number from 0 to 6

3

In [ ]:
np.random.randint(10,20,5) #generates 5 random numbers btw 10n to 20

array([19, 13, 15, 13, 18])

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0) #column wise axis

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1) #row wise

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6*5)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
import numpy as np
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3::2]

array([14, 16, 18, 20])

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
slice=arr[1:4, 3:4]
slice

array([[ 9],
       [14],
       [19]])

In [ ]:
bool_index=arr% 2==0
bool_index


array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr=arr[bool_index]
arr


array([12, 14, 16, 18, 20])

In [ ]:
from binascii import a2b_base64
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1+a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1-a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [ ]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [ ]:
arr+10

array([20, 30, 40, 50])

In [ ]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.column_stack((a,b))


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85] ])   # Student 5

In [ ]:
data.shape

(5, 3)

In [ ]:
np.mean(data[:,0])

np.float64(18.4)

In [ ]:
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
np.max(data[:,2])

np.int64(95)

In [ ]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [ ]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])